#!/bin/bash
#
# This script export the conda environment in a yml file with data and platform
#

# Environment to export:
envname="obidam36"

# Machine hardware name
hard="$(uname -m)"

# Machine type
unameOut="$(uname -s)"
case "${unameOut}" in
    Linux*)     machine=Linux;;
    Darwin*)    machine=Mac;;
    CYGWIN*)    machine=Cygwin;;
    MINGW*)     machine=MinGw;;
    *)          machine="UNKNOWN:${unameOut}"
esac

# Date of creation
DATE=`date '+%Y%m%d_%H%M%S'`

# Compute export filename
ymlfile="${envname}_${hard}_${machine}_${DATE}.yml"

# Export
conda env export -n $envname | grep -v "^prefix: " > $ymlfile
echo "Conda environment $envname exported to: $ymlfile"

# Exit gracefully
exit 0