#!/bin/bash
#
# Update github repo with last export of environment
#
# This script must be ran from the utils directory

# Get last version of the environment for this platform

# Environement to export:
envname="obidam"

# Machine hardware name
hard="$(uname -m)"

# Machine type
unameOut="$(uname -s)"
case "${unameOut}" in
    Linux*)     machine=Linux;;
    Darwin*)    machine=Mac;;
    CYGWIN*)    machine=Cygwin;;
    MINGW*)     machine=MinGw;;
    *)          machine="UNKNOWN:${unameOut}"
esac

# Date of creation
DATE=`date '+%Y%m%d%H%M%S'`

# Compute export filename
ymldir="${hard}_${machine}"
ymlfile="${envname}_${hard}_${machine}_${DATE}.yml"
ymlfilelast="${envname}_${hard}_${machine}_last.yml"

# Export
conda env export -n $envname | grep -v "^prefix: " > ../$ymldir/$ymlfile
echo "Conda environment $envname exported to: $ymldir/$ymlfile"

# Update last version file
\cp ../$ymldir/$ymlfile ../$ymlfilelast

# Update the git repo:
git pull --rebase origin master
git add ../$ymldir/$ymlfile
git add ../$ymlfilelast
git commit -m "Automatic update to ${ymldir} environment"
git push origin master

# Exit gracefully
exit 0




